permalink: /blog/:year/:month/:day/:title

baseurl: ""

# Build settings
markdown: kramdown

# Site specific context
title: Julia Elman
description: Julia Elman is a Senior UI Developer, technical writer and public speaker based in Durham, North Carolina. 